name: .NET Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test

    - name: Integration Tests
      run: dotnet test Album.Api.Tests